services:
  proxy:
    build: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./traefik.toml:/etc/traefik/traefik.toml
      - ./cert/:/cert/
    env_file:
      - ./local.env

  dev1:
    image: ghcr.io/sil-org/php8:8.3
    ports:
      - "80"
    volumes:
      - ./index.php:/data/frontend/web/index.php

  dev2:
    image: ghcr.io/sil-org/php8:8.3
    ports:
      - "80"
    volumes:
      - ./index.php:/data/frontend/web/index.php

  dev3:
    image: ghcr.io/sil-org/php8:8.3
    ports:
      - "80"
    volumes:
      - ./index.php:/data/frontend/web/index.php
