version: "3"

services:

  proxy:
    build: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./traefik.toml:/etc/traefik/traefik.toml
      - ./cert/:/cert/
    env_file:
      - ./local.env

  dev1:
    image: silintl/php8:8.1
    ports:
     - "80"
    volumes:
      - ./index.php:/data/frontend/web/index.php

  dev2:
    image: silintl/php8:8.1
    ports:
     - "80"
    volumes:
      - ./index.php:/data/frontend/web/index.php

  dev3:
    image: silintl/php8:8.1
    ports:
     - "80"
    volumes:
      - ./index.php:/data/frontend/web/index.php
