FROM golang:1-alpine3.22
WORKDIR /go/src/entrypoint
COPY ./go.mod /go/src/entrypoint
COPY ./entrypoint.go /go/src/entrypoint/
COPY ./entrypoint_test.go /go/src/entrypoint/
COPY ./traefik.toml /go/src/entrypoint/
COPY ./traefik_test.toml /go/src/entrypoint/
CMD ["go", "test"]
